# Generated by Django 5.0 on 2023-12-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
