# Generated by Django 5.0 on 2023-12-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_test_data_test_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='views',
            field=models.FloatField(default=0),
        ),
    ]
